### ISSUE TITLE
About the opensource code

### ISSUE THREAD

**Issue by zhangxujinsh** [Talegqz/neural_novel_actor#1]
@Talegqz 
Dear Dr.Gao
     Do you have the plan to release the code! I am intersted in the project!
    
Bob

**Comment by Talegqz** [comment]
Thanks for your attention, we will release code in this month as soon as possible.

**Comment by zhangxujinsh** [comment]
@Talegqz @19reborn 
Dear Dr.Gao, Dr.Wang
Thank you for  your releasing the test code and pretrained model. 
Will you release the training code and the trainning dataset?

Bob
